name: Release
run-name: Release ${{ github.event.release.tag_name }}
on:
  release:
    types: [ published ]
jobs:
  build_image:
    uses: ./.github/workflows/build_image.yml
    with:
      tag: ${{ github.event.release.tag_name }}
      registry: ${{ vars.DOCKER_REGISTRY }}
      app_name: ${{ vars.APP_NAME }}
      registry_namespace: ${{ vars.DOCKER_REGISTRY_NAMESPACE }}
  deploy:
    needs: [ build_image ]
    uses: ./.github/workflows/deploy_image.yml
    with:
      tag: ${{ github.event.release.tag_name }}
      registry: ${{ vars.DOCKER_REGISTRY }}
      app_name: ${{ vars.APP_NAME }}
      registry_namespace: ${{ vars.DOCKER_REGISTRY_NAMESPACE }}
    secrets:
      username: ${{ secrets.DOCKER_REGISTRY_USER }}
      password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
